import { useMemo, useState, type FormEvent } from "react";
import { HealthRecordService } from "../local-domain/health-record-service";

interface Profile { id: string; name: string; relationship: string }
interface Message { role: "user" | "assistant"; content: string }
interface Draft { body_area?: string | null; intensity?: number | null; sensation?: string | null; onset_description?: string | null; aggravating_factors?: string | null; note?: string | null }

export function PainChatPanel({ householdId, profiles }: { householdId: string; profiles: Profile[] }) {
  const service = useMemo(() => new HealthRecordService(), []);
  const [open, setOpen] = useState(false); const [profileId, setProfileId] = useState(profiles[0]?.id ?? "");
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "어디가 어떻게 아픈지 편하게 말씀해 주세요. 진단이 아니라 기록 작성을 도와드려요." }]);
  const [input, setInput] = useState(""); const [draft, setDraft] = useState<Draft>({}); const [missing, setMissing] = useState<string[]>(["body_area", "intensity"]); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [saved, setSaved] = useState(false);
  const send = async (event: FormEvent) => { event.preventDefault(); const content = input.trim(); if (!content || loading) return; const next = [...messages, { role: "user" as const, content }]; setMessages(next); setInput(""); setLoading(true); setError(""); try { const response = await fetch("http://127.0.0.1:8000/api/v1/pain-chat/messages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? "대화에 실패했습니다."); setMessages((current) => [...current, { role: "assistant", content: body.data.assistant_message }]); setDraft(body.data.draft); setMissing(body.data.missing_fields); setNotice(body.data.emergency_notice ?? ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "대화에 실패했습니다."); } finally { setLoading(false); } };
  const save = async () => { if (!draft.body_area || draft.intensity === null || draft.intensity === undefined) return; const result = await service.create({ householdId, profileId, recordedAt: new Date(`${new Date().toISOString().slice(0, 10)}T12:00:00`).toISOString(), source: "local_ai", payload: { type: "pain", bodyArea: draft.body_area, intensity: draft.intensity, sensation: draft.sensation || undefined, aggravatingFactors: draft.aggravating_factors || undefined, note: [draft.onset_description && `시작: ${draft.onset_description}`, draft.note].filter(Boolean).join("\n") || undefined }, duplicatePolicy: "reject" }); if (!result.ok) return setError(result.error.message); setSaved(true); };
  return <><button className="pain-chat-launcher" onClick={() => setOpen(true)}>대화로 통증 기록</button>{open && <div className="modal-backdrop"><section className="pain-chat-panel" role="dialog" aria-modal="true"><header><div><p className="eyebrow">OpenAI 대화형 입력</p><h2>통증 기록 도우미</h2></div><button aria-label="닫기" onClick={() => setOpen(false)}>×</button></header><p className="chat-disclosure">입력 내용은 기록 초안 생성을 위해 OpenAI API로 전송됩니다. 진단을 하지 않으며 저장 전 직접 확인해야 합니다.</p><label>기록 대상<select value={profileId} onChange={(event) => setProfileId(event.target.value)}>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · {profile.relationship}</option>)}</select></label><div className="chat-messages">{messages.map((message, index) => <p className={message.role} key={index}>{message.content}</p>)}</div>{notice && <p className="chat-emergency">{notice}</p>}<form onSubmit={(event) => void send(event)}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="예: 어제부터 오른쪽 윗배가 찌르듯이 아파요" /><button className="primary" disabled={loading}>{loading ? "정리 중…" : "보내기"}</button></form>{error && <p className="form-error">{error}</p>}{(draft.body_area || draft.intensity !== undefined) && <section className="chat-confirm"><h3>저장 전 확인</h3><label>통증 부위<input value={draft.body_area ?? ""} onChange={(event) => setDraft({ ...draft, body_area: event.target.value })} /></label><label>강도<input type="number" min="0" max="10" value={draft.intensity ?? ""} onChange={(event) => setDraft({ ...draft, intensity: Number(event.target.value) })} /></label><label>통증 양상<input value={draft.sensation ?? ""} onChange={(event) => setDraft({ ...draft, sensation: event.target.value })} /></label><label>심해지는 상황<input value={draft.aggravating_factors ?? ""} onChange={(event) => setDraft({ ...draft, aggravating_factors: event.target.value })} /></label>{missing.length > 0 && <p>추가 질문 필요: {missing.map((value) => value === "body_area" ? "통증 부위" : "통증 강도").join(", ")}</p>}<button className="primary" disabled={Boolean(missing.length) || saved} onClick={() => void save()}>{saved ? "저장 완료" : "통증 기록으로 저장"}</button></section>}</section></div>}</>;
}
