"""add source_document_id to health_records

Revision ID: b812213ae8dc
Revises: c7b87355d7a0
Create Date: 2026-09-08 15:32:09.353255+09:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b812213ae8dc"
down_revision: Union[str, Sequence[str], None] = "c7b87355d7a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("health_records", sa.Column("source_document_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_records", "source_document_id")
    # ### end Alembic commands ###
