"""initial service_accounts and subscriptions

Revision ID: ba4d3280e8b8
Revises: 
Create Date: 2026-08-18 17:09:48.827426+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4d3280e8b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'closed', name='service_account_status', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_accounts')),
    sa.UniqueConstraint('email', name=op.f('uq_service_accounts_email'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'BASIC', 'FAMILY', name='subscription_plan', native_enum=False, create_constraint=True, length=20), server_default='FREE', nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscription_status', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['service_accounts.id'], name=op.f('fk_subscriptions_account_id_service_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('account_id', name=op.f('uq_subscriptions_account_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###
