"""add households and family invitations

Revision ID: 0bf56173f28b
Revises: ba4d3280e8b8
Create Date: 2026-08-19 02:23:58.963661+09:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0bf56173f28b"
down_revision: Union[str, Sequence[str], None] = "ba4d3280e8b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "closed", name="household_status", native_enum=False, create_constraint=True, length=20),
            server_default="active",
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'active' AND closed_at IS NULL) OR (status = 'closed' AND closed_at IS NOT NULL)",
            name=op.f("ck_households_household_status_closed_at_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_households_created_by_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    op.create_table(
        "family_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("inviter_account_id", sa.Uuid(), nullable=False),
        sa.Column("invitee_email", sa.String(length=255), nullable=False),
        sa.Column("target_profile_ref", sa.String(length=86), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "declined",
                "expired",
                "cancelled",
                name="family_invitation_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'pending' AND accepted_at IS NULL AND declined_at IS NULL AND cancelled_at IS NULL AND accepted_by_account_id IS NULL) OR (status = 'accepted' AND accepted_at IS NOT NULL AND accepted_by_account_id IS NOT NULL AND declined_at IS NULL AND cancelled_at IS NULL) OR (status = 'declined' AND declined_at IS NOT NULL AND accepted_at IS NULL AND cancelled_at IS NULL AND accepted_by_account_id IS NULL) OR (status = 'cancelled' AND cancelled_at IS NOT NULL AND accepted_at IS NULL AND declined_at IS NULL AND accepted_by_account_id IS NULL) OR (status = 'expired' AND accepted_at IS NULL AND declined_at IS NULL AND cancelled_at IS NULL AND accepted_by_account_id IS NULL)",
            name=op.f("ck_family_invitations_terminal_state_consistent"),
        ),
        sa.CheckConstraint(
            "target_profile_ref ~ '^[A-Za-z0-9_-]{43,86}$'",
            name=op.f("ck_family_invitations_target_profile_ref_format"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_family_invitations_family_invitation_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name=op.f("ck_family_invitations_family_invitation_token_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_family_invitations_accepted_by_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_family_invitations_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["inviter_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_family_invitations_inviter_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_family_invitations_token_hash")),
    )
    op.create_index(op.f("ix_family_invitations_expires_at"), "family_invitations", ["expires_at"], unique=False)
    op.create_index(op.f("ix_family_invitations_household_id"), "family_invitations", ["household_id"], unique=False)
    op.create_index(op.f("ix_family_invitations_invitee_email"), "family_invitations", ["invitee_email"], unique=False)
    op.create_index(
        op.f("ix_family_invitations_inviter_account_id"), "family_invitations", ["inviter_account_id"], unique=False
    )
    op.create_index(
        "uq_family_invitations_pending_target",
        "family_invitations",
        ["household_id", sa.literal_column("lower(invitee_email)"), "target_profile_ref"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "household_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "left",
                name="household_membership_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'active' AND left_at IS NULL) OR (status = 'left' AND left_at IS NOT NULL)",
            name=op.f("ck_household_memberships_status_left_at_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["service_accounts.id"],
            name=op.f("fk_household_memberships_account_id_service_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_household_memberships_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_household_memberships")),
        sa.UniqueConstraint("household_id", "account_id", name="uq_household_memberships_household_account"),
    )
    op.create_index(op.f("ix_household_memberships_account_id"), "household_memberships", ["account_id"], unique=False)
    op.create_index(
        op.f("ix_household_memberships_household_id"), "household_memberships", ["household_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_household_memberships_household_id"), table_name="household_memberships")
    op.drop_index(op.f("ix_household_memberships_account_id"), table_name="household_memberships")
    op.drop_table("household_memberships")
    op.drop_index(
        "uq_family_invitations_pending_target",
        table_name="family_invitations",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_family_invitations_inviter_account_id"), table_name="family_invitations")
    op.drop_index(op.f("ix_family_invitations_invitee_email"), table_name="family_invitations")
    op.drop_index(op.f("ix_family_invitations_household_id"), table_name="family_invitations")
    op.drop_index(op.f("ix_family_invitations_expires_at"), table_name="family_invitations")
    op.drop_table("family_invitations")
    op.drop_table("households")
    # ### end Alembic commands ###
