"""align profile_links and family_invitation indexes with models

Revision ID: 81b45913091c
Revises: c3d5e7f91a24
Create Date: 2026-08-27 13:49:11.373752+09:00

**모델은 바뀌었는데 마이그레이션이 없어서 `alembic check` 가 깨져 있었다.** CI 의
"Verify no model/migration drift" 단계가 그것을 잡는 유일한 장치인데(테스트는
`create_all` 로 스키마를 만들어서 이 어긋남을 못 본다) 빨간불이었다. 이 리비전은
그 격차를 메운다 — 대부분 이름 변경과 인덱스 정리다.

**다만 하나는 이름 변경이 아니라 의미 변경이다.** 짚어 둔다.

    (전) uq_family_invitations_pending_target
         household_id + lower(invitee_email) + target_profile_ref, **status='pending' 일 때만**
    (후) uq_family_invitations_profile_ref_lifetime
         household_id + target_profile_ref, **조건 없이 전 기간**

전에는 거절·취소된 초대와 같은 프로필로 다시 초대할 수 있었지만 이제 못 한다. 한
가구에서 한 프로필 참조는 평생 한 번만 초대된다(이름의 `lifetime` 이 그 뜻이다).
모델이 그렇게 선언하고 있으므로 마이그레이션을 모델에 맞춘 것이고, 반대 방향이
맞다면 고칠 곳은 `app/models/family_invitations.py` 의 인덱스 선언이다.

**기존 데이터가 있는 DB 에서는 이 인덱스 생성이 실패할 수 있다** — 같은 (가구,
프로필 참조) 로 만들어진 초대가 둘 이상이면 그렇다. 배포 전에 확인하라.

    select household_id, target_profile_ref, count(*)
      from family_invitations group by 1, 2 having count(*) > 1;
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81b45913091c"
down_revision: Union[str, Sequence[str], None] = "c3d5e7f91a24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_family_invitations_pending_target"),
        table_name="family_invitations",
        postgresql_where="((status)::text = 'pending'::text)",
    )
    op.create_index(
        "uq_family_invitations_profile_ref_lifetime",
        "family_invitations",
        ["household_id", "target_profile_ref"],
        unique=True,
    )
    # 자동 생성본은 `create_constraint=True` 였는데 그러면
    # `ck_profile_links_profile_link_status` 를 **다시 만들려다 DuplicateObjectError** 로
    # 죽는다 — 그 CHECK 는 91c8e40c547a 가 이미 만들어 뒀다. 여기서 실제로 필요한 변경은
    # 길이(16 → 20)뿐이므로 제약 생성을 끈다.
    op.alter_column(
        "profile_links",
        "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.Enum(
            "active", "unlinked", name="profile_link_status", native_enum=False, create_constraint=False, length=20
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.drop_index(op.f("ix_profile_links_account_status"), table_name="profile_links")
    op.drop_index(
        op.f("uq_profile_links_one_active_account_per_profile"),
        table_name="profile_links",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_index(
        op.f("uq_profile_links_one_active_profile_per_account_household"),
        table_name="profile_links",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(op.f("ix_profile_links_account_id"), "profile_links", ["account_id"], unique=False)
    op.create_index(
        "uq_profile_links_active_household_account",
        "profile_links",
        ["household_id", "account_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_unique_constraint(
        "uq_profile_links_household_profile_ref", "profile_links", ["household_id", "local_profile_ref"]
    )
    op.drop_constraint(op.f("ck_profile_links_local_profile_ref_format"), "profile_links", type_="check")
    op.create_check_constraint(
        op.f("ck_profile_links_profile_link_ref_format"),
        "profile_links",
        "local_profile_ref ~ '^[A-Za-z0-9_-]{43,86}$'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_profile_links_profile_link_ref_format"), "profile_links", type_="check")
    op.create_check_constraint(
        op.f("ck_profile_links_local_profile_ref_format"),
        "profile_links",
        "local_profile_ref::text ~ '^[A-Za-z0-9_-]{43,86}$'::text",
    )
    op.drop_constraint("uq_profile_links_household_profile_ref", "profile_links", type_="unique")
    op.drop_index(
        "uq_profile_links_active_household_account",
        table_name="profile_links",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_profile_links_account_id"), table_name="profile_links")
    op.create_index(
        op.f("uq_profile_links_one_active_profile_per_account_household"),
        "profile_links",
        ["household_id", "account_id"],
        unique=True,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(
        op.f("uq_profile_links_one_active_account_per_profile"),
        "profile_links",
        ["household_id", "local_profile_ref"],
        unique=True,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(op.f("ix_profile_links_account_status"), "profile_links", ["account_id", "status"], unique=False)
    op.alter_column(
        "profile_links",
        "status",
        existing_type=sa.Enum(
            "active", "unlinked", name="profile_link_status", native_enum=False, create_constraint=False, length=20
        ),
        type_=sa.VARCHAR(length=16),
        existing_nullable=False,
        existing_server_default=sa.text("'active'::character varying"),
    )
    op.drop_index("uq_family_invitations_profile_ref_lifetime", table_name="family_invitations")
    op.create_index(
        op.f("uq_family_invitations_pending_target"),
        "family_invitations",
        ["household_id", sa.literal_column("lower(invitee_email::text)"), "target_profile_ref"],
        unique=True,
        postgresql_where="((status)::text = 'pending'::text)",
    )
    # ### end Alembic commands ###
