"""add_family_profiles_and_health_records

Revision ID: 6b3d62092d34
Revises: 2c76fb29f545
Create Date: 2026-09-06 14:03:58.160055+09:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b3d62092d34"
down_revision: Union[str, Sequence[str], None] = "2c76fb29f545"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column("relationship", sa.String(length=30), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("birth_date", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("row_version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_family_profiles_created_by_account_id_service_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_family_profiles_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_profiles")),
    )
    op.create_index(
        "ix_family_profiles_account_status", "family_profiles", ["created_by_account_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_family_profiles_created_by_account_id"), "family_profiles", ["created_by_account_id"], unique=False
    )
    op.create_index(op.f("ix_family_profiles_household_id"), "family_profiles", ["household_id"], unique=False)
    op.create_index("ix_family_profiles_household_status", "family_profiles", ["household_id", "status"], unique=False)
    op.create_table(
        "family_histories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("relative_relationship", sa.String(length=30), nullable=False),
        sa.Column("condition_name", sa.String(length=100), nullable=False),
        sa.Column("onset_age", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["family_profiles.id"],
            name=op.f("fk_family_histories_profile_id_family_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_histories")),
    )
    op.create_index(
        "ix_family_histories_profile_condition", "family_histories", ["profile_id", "condition_name"], unique=False
    )
    op.create_index(op.f("ix_family_histories_profile_id"), "family_histories", ["profile_id"], unique=False)
    op.create_table(
        "health_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=30), server_default="manual", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("row_version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["family_profiles.id"],
            name=op.f("fk_health_records_profile_id_family_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_records")),
    )
    op.create_index(op.f("ix_health_records_profile_id"), "health_records", ["profile_id"], unique=False)
    op.create_index("ix_health_records_profile_status", "health_records", ["profile_id", "status"], unique=False)
    op.create_index(
        "ix_health_records_profile_type_date",
        "health_records",
        ["profile_id", "record_type", "recorded_at"],
        unique=False,
    )
    op.create_index(op.f("ix_health_records_record_type"), "health_records", ["record_type"], unique=False)
    op.create_index(op.f("ix_health_records_recorded_at"), "health_records", ["recorded_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_health_records_recorded_at"), table_name="health_records")
    op.drop_index(op.f("ix_health_records_record_type"), table_name="health_records")
    op.drop_index("ix_health_records_profile_type_date", table_name="health_records")
    op.drop_index("ix_health_records_profile_status", table_name="health_records")
    op.drop_index(op.f("ix_health_records_profile_id"), table_name="health_records")
    op.drop_table("health_records")
    op.drop_index(op.f("ix_family_histories_profile_id"), table_name="family_histories")
    op.drop_index("ix_family_histories_profile_condition", table_name="family_histories")
    op.drop_table("family_histories")
    op.drop_index("ix_family_profiles_household_status", table_name="family_profiles")
    op.drop_index(op.f("ix_family_profiles_household_id"), table_name="family_profiles")
    op.drop_index(op.f("ix_family_profiles_created_by_account_id"), table_name="family_profiles")
    op.drop_index("ix_family_profiles_account_status", table_name="family_profiles")
    op.drop_table("family_profiles")
    # ### end Alembic commands ###
